// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntentStatus } from "../../../src/types/bindings";

/**
 * Every failure the frontend is allowed to see.
 *
 * `#[non_exhaustive]` so adding a variant is not a breaking change for
 * downstream matches, and `tag = "kind"` so TypeScript gets a union it can
 * switch on.
 */
export type AppError = { "kind": "not_ready", "detail": { subsystem: string, } } | { "kind": "unsupported", "detail": { feature: string, } } | { "kind": "mesh_offline" } | { "kind": "invalid_intent", "detail": { field: string, reason: InvalidReason, } } | { "kind": "chain", "detail": { retryable: boolean, } } | { "kind": "vault_locked" } | { "kind": "too_many_subscriptions", "detail": { limit: number, } } | { "kind": "internal" };

export type AssetOption = { name: string, 
/**
 * Three-letter tag the board shows beside the name.
 */
tag: string, decimals: number, 
/**
 * The spendable balance, pre-formatted — what MAX fills in.
 *
 * Absent rather than zero when the balance is unknown, which is what an
 * asset this wallet has never held looks like. Rendering an unknown
 * balance as `0` would tell the user they have none, which is a different
 * claim entirely.
 */
available: string | null, };

/**
 * Delta direction. Domain matches `StatBlock`'s `deltaTone`.
 */
export type DeltaTone = "up" | "down" | "neutral";

/**
 * The options the compose screen offers.
 */
export type FormOptions = { actions: Array<string>, assets: Array<AssetOption>, conditions: Array<string>, modes: Array<ModeOption>, privacyLevels: Array<string>, };

/**
 * Everything the detail screen renders.
 */
export type IntentDetailView = { id: string, title: string, status: IntentStatus, 
/**
 * Counts up while live, freezes at the terminal state.
 */
elapsed: string, 
/**
 * The seven-row breakdown.
 */
rows: Array<ReviewRow>, 
/**
 * Whether settling is possible right now.
 */
canSettle: boolean, 
/**
 * Why not, in brand voice, when it is not. Absent when it is.
 */
settleBlocked: string | null, 
/**
 * Whether the intent can still be cancelled.
 */
canCancel: boolean, };

/**
 * The compose form's fields, exactly as the screen holds them.
 *
 * One type rather than seven parameters on two commands. That is what makes
 * "preview and broadcast see the same input" a property of the signature
 * instead of something a caller has to get right twice.
 */
export type IntentFields = { action: string, asset: string, condition: string, 
/**
 * Ignored when the condition carries no price.
 */
price: string, amount: string, mode: string, privacy: string, };

/**
 * Which slice of the list to return.
 */
export type IntentFilter = "ACTIVE" | "PENDING" | "HISTORY";

/**
 * What the confirm dialog renders.
 */
export type IntentPreview = { rows: Array<ReviewRow>, 
/**
 * The dialog's closing line, chosen by whether this will broadcast now.
 */
confirm: string, 
/**
 * Whether confirming broadcasts immediately or queues locally. Drives the
 * button's own verb, so the dialog does not promise one thing in prose and
 * another on the control.
 */
willBroadcast: boolean, };

/**
 * An intent as a list row renders it.
 */
export type IntentView = { id: string, 
/**
 * e.g. `BUY AVAX`.
 */
title: string, 
/**
 * e.g. `UNDER $95`.
 */
subtitle: string, 
/**
 * Execution mode, shown as a badge. Absent when default.
 */
badge: string | null, amount: string, 
/**
 * The lifecycle state, driving both the status text and the dot tone.
 */
status: IntentStatus, 
/**
 * Elapsed or settled time, e.g. `2M 14S` or `11.4S`.
 */
elapsed: string, };

/**
 * Why an intent was rejected. A variant rather than a sentence, so the form
 * can render on-voice copy per field.
 */
export type InvalidReason = "missing" | "malformed" | "out_of_range" | "too_precise" | "insufficient_funds";

/**
 * One rendered terminal line.
 *
 * `Box<str>` rather than `String`: these are built once, never mutated, and
 * arrive in the hundreds, so `String`'s spare-capacity word is dead weight.
 */
export type LogLine = { text: string, tone: LogTone, };

/**
 * Terminal line tone. Domain matches `TerminalLine`.
 */
export type LogTone = "out" | "dim" | "ok" | "err" | "info" | "loud";

/**
 * What the home screen renders.
 */
export type MeshSnapshotView = { 
/**
 * Truncated for display, e.g. `7F3A..8C2E`.
 */
nodeId: string, 
/**
 * Uptime in the board's format, e.g. `3D 14H 22M`.
 */
uptime: string, connected: boolean, stats: Array<StatTile>, };

export type ModeOption = { label: string, description: string, };

/**
 * A peer, as the nodes screen shows it.
 *
 * **No distance.** A libp2p peer has an identifier and an address, not
 * coordinates, and this app requests no location permission — asking for one
 * would contradict the entire premise. The prototype's `1.2 km` is canned;
 * rendering it would be a fabricated measurement.
 */
export type NodeSummary = { 
/**
 * Truncated peer id, e.g. `8A3F..1209`.
 */
id: string, 
/**
 * Round-trip time where known.
 */
latencyMs: number | null, 
/**
 * 1 is direct; more means relayed.
 */
hops: number, transport: Transport, 
/**
 * Deterministic map position in [0,1], seeded by peer id.
 */
x: number, y: number, 
/**
 * Milliseconds, also seeded, so the field does not pulse in unison.
 */
pulseMs: number, };

/**
 * What the profile screen shows.
 */
export type ProfileView = { nodeId: string, 
/**
 * `87.6 (+5.3%)`, or an em dash with no mesh. Mocked per ticket 03 — see
 * src/reputation.rs for what that means and ticket 39 to replace it.
 */
reputation: string, memberSince: string, offline: boolean, network: string, 
/**
 * Whether transactions here move real value.
 */
isTestnet: boolean, };

/**
 * What the proof screen renders.
 */
export type ProofView = { id: string, 
/**
 * The settling transaction's hash.
 */
hash: string, 
/**
 * How long settlement took, e.g. `11.4S`.
 */
timing: string, 
/**
 * The hops the intent travelled. Empty when it settled directly.
 */
route: Array<string>, 
/**
 * The price it filled at. Absent for an unconditioned intent, which has
 * no price to have filled at.
 */
filledAt: string | null, };

/**
 * One row of the confirm dialog.
 */
export type ReviewRow = { key: string, value: string, };

/**
 * What the splash screen needs to decide what it is offering.
 */
export type SessionStatus = { 
/**
 * Whether bootstrap has finished and the mesh is usable.
 */
ready: boolean, 
/**
 * Truncated node id, e.g. `7F3A..8C2E`. Absent before bootstrap.
 */
nodeId: string | null, 
/**
 * Whether a peer is reachable right now.
 */
connected: boolean, };

/**
 * A home-screen stat tile, pre-formatted.
 *
 * The frontend renders these verbatim. Sending a raw number and formatting it
 * there would mean reimplementing the separator and precision rules per
 * screen, and drifting from them.
 */
export type StatTile = { label: string, 
/**
 * Already separated, e.g. `1,248`.
 */
value: string, 
/**
 * Already signed and suffixed, e.g. `+12.4%`. Absent when unmeasured.
 */
delta: string | null, deltaTone: DeltaTone, };

/**
 * Status tone. Domain matches the design system's `StatusDot` prop exactly.
 */
export type StatusTone = "online" | "alert" | "info" | "idle" | "offline";

/**
 * Toast tone. Domain matches `Toast`.
 */
export type ToastTone = "neutral" | "info" | "success" | "alert";

/**
 * How a peer is reached.
 */
export type Transport = "mdns" | "quic" | "relayed";

/**
 * A row in the vault list.
 */
export type VaultRow = { 
/**
 * Three-letter tag, e.g. `AVX`, `ID`, `KEY`.
 */
tag: string, name: string, amount: string, 
/**
 * Secondary line. Absent when there is nothing true to say.
 */
detail: string | null, };
