// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every failure the frontend is allowed to see.
 *
 * `#[non_exhaustive]` so adding a variant is not a breaking change for
 * downstream matches, and `tag = "kind"` so TypeScript gets a union it can
 * switch on.
 */
export type AppError = { "kind": "not_ready", "detail": { subsystem: string, } } | { "kind": "unsupported", "detail": { feature: string, } } | { "kind": "mesh_offline" } | { "kind": "invalid_intent", "detail": { field: string, reason: InvalidReason, } } | { "kind": "chain", "detail": { retryable: boolean, } } | { "kind": "vault_locked" } | { "kind": "too_many_subscriptions", "detail": { limit: number, } } | { "kind": "internal" };

/**
 * A Marketplace listing, always backed by a real CabalMeshVoucher tokenId
 * the seller owns on-chain (enforced by the contract itself at list time).
 */
export type AssetListingView = { id: number, seller: string, description: string, priceWei: string, priceAvax: string, tokenId: number, };

export type AssetOption = { name: string, 
/**
 * Three-letter tag the board shows beside the name.
 */
tag: string, decimals: number, 
/**
 * The spendable balance, pre-formatted — what MAX fills in.
 *
 * Absent rather than zero when the balance is unknown, which is what an
 * asset this wallet has never held looks like. Rendering an unknown
 * balance as `0` would tell the user they have none, which is a different
 * claim entirely.
 */
available: string | null, };

/**
 * What the nodes screen shows about the offline plane.
 *
 * Every field is a measurement. There is no "signal strength" and no
 * "distance": the radio reports neither, and the app requests no location
 * permission — asking for one would contradict the premise.
 */
export type BleStatusView = { 
/**
 * Whether the plane is running at all.
 *
 * False means no radio backend and no development transport — a state
 * the app is expected to survive, and one the screen has to be able to
 * say out loud rather than rendering as "no peers".
 */
running: boolean, 
/**
 * This session's identifier, truncated. Changes on every launch.
 */
nodeId: string, 
/**
 * Which backend is carrying the plane, verbatim: `loopback`, or the name
 * of a real radio. Never dressed up as "BLE" when it is not.
 */
transport: string, 
/**
 * Radio links currently open.
 */
links: number, 
/**
 * Peers one hop away — people in the room.
 */
directPeers: number, 
/**
 * Every peer reachable, direct or through a neighbour.
 */
reachablePeers: number, 
/**
 * Reachable peers offering a way to the internet.
 */
gateways: number, 
/**
 * Packets forwarded for other people.
 */
relayed: bigint, 
/**
 * Forwards cancelled because a neighbour was faster.
 *
 * Shown beside `relayed` because without it the two states "the mesh is
 * quiet" and "everything is arriving twice and being suppressed" look
 * identical.
 */
suppressed: bigint, offline: boolean, };

/**
 * A Marketplace deal (real on-chain state: Active/Released/Refunded) —
 * the real "someone is transacting on this listing" signal.
 */
export type DealView = { 
/**
 * u32 — see [`AssetListingView::id`]'s comment for why.
 */
dealId: number, buyer: string, seller: string, tokenId: number, amountAvax: string, status: string, role: string, };

/**
 * Delta direction. Domain matches `StatBlock`'s `deltaTone`.
 */
export type DeltaTone = "up" | "down" | "neutral";

/**
 * One slot's currently equipped module.
 */
export type EquippedSlot = { slot: number, tokenId: number, };

/**
 * Why an intent failed. A variant rather than a message, so the UI can render
 * on-voice copy instead of echoing an internal string.
 */
export type FailureReason = "no_route" | "node_failure" | "condition_unmet" | "settlement_rejected" | "insufficient_balance";

/**
 * The options the compose screen offers.
 */
export type FormOptions = { actions: Array<string>, assets: Array<AssetOption>, conditions: Array<string>, modes: Array<ModeOption>, privacyLevels: Array<string>, };

/**
 * A nearby node the user could pick as a guardian.
 */
export type GuardianCandidate = { 
/**
 * Full peer id — opaque to the UI, round-tripped back verbatim to
 * `guardian_enroll`. Never shown; `label` is what renders.
 */
peerId: string, 
/**
 * Truncated for display, e.g. `7F3A…C2E1`.
 */
label: string, hops: number, };

/**
 * Who accepted an enrollment invitation, and who did not answer.
 */
export type GuardianEnrollResult = { enrolled: Array<string>, noReply: Array<string>, };

/**
 * What `SECURITY` shows about the guardian scheme, in both roles this
 * device can play.
 */
export type GuardianStatus = { enrolled: boolean, guardianCount: number, threshold: number, 
/**
 * How many other owners this device holds a share for.
 */
holdingFor: number, };

/**
 * Payload for the `guardian-unlock-request` event: this device's own tag
 * matched someone's unlock broadcast and a human needs to decide.
 *
 * `from` is a truncated peer id for display only — never the durable
 * identity of whoever is asking, because there is no durable identity to
 * show. It is exactly as anonymous to this screen as the mesh itself keeps
 * everyone by default.
 */
export type GuardianUnlockPrompt = { id: number, from: string, };

/**
 * Everything the detail screen renders.
 */
export type IntentDetailView = { id: string, title: string, status: IntentStatus, 
/**
 * Counts up while live, freezes at the terminal state.
 */
elapsed: string, 
/**
 * The seven-row breakdown.
 */
rows: Array<ReviewRow>, 
/**
 * Whether settling is possible right now.
 */
canSettle: boolean, 
/**
 * Why not, in brand voice, when it is not. Absent when it is.
 */
settleBlocked: string | null, 
/**
 * Whether the intent can still be cancelled.
 */
canCancel: boolean, };

/**
 * The compose form's fields, exactly as the screen holds them.
 *
 * One type rather than seven parameters on two commands. That is what makes
 * "preview and broadcast see the same input" a property of the signature
 * instead of something a caller has to get right twice.
 */
export type IntentFields = { action: string, asset: string, condition: string, 
/**
 * Ignored when the condition carries no price.
 */
price: string, amount: string, mode: string, privacy: string, };

/**
 * Which slice of the list to return.
 */
export type IntentFilter = "ACTIVE" | "PENDING" | "HISTORY";

/**
 * What the confirm dialog renders.
 */
export type IntentPreview = { rows: Array<ReviewRow>, 
/**
 * The dialog's closing line, chosen by whether this will broadcast now.
 */
confirm: string, 
/**
 * Whether confirming broadcasts immediately or queues locally. Drives the
 * button's own verb, so the dialog does not promise one thing in prose and
 * another on the control.
 */
willBroadcast: boolean, };

/**
 * Where an intent is in its life.
 *
 * Matched exhaustively everywhere — no catch-all arm — so adding a variant
 * surfaces every place that has to decide what it means, rather than silently
 * falling through to a default.
 */
export type IntentStatus = { "status": "DRAFT" } | { "status": "BROADCAST", route_len: number, } | { "status": "NEGOTIATING", bids: number, best: UsdPrice | null, } | { "status": "FINDING_ROUTE" } | { "status": "WAITING" } | { "status": "SETTLED", proof: ProofHash, filled_at: UsdPrice, elapsed_ms: number, } | { "status": "FAILED", reason: FailureReason, } | { "status": "CANCELLED" };

/**
 * An intent as a list row renders it.
 */
export type IntentView = { id: string, 
/**
 * e.g. `BUY AVAX`.
 */
title: string, 
/**
 * e.g. `UNDER $95`.
 */
subtitle: string, 
/**
 * Execution mode, shown as a badge. Absent when default.
 */
badge: string | null, amount: string, 
/**
 * The lifecycle state, driving both the status text and the dot tone.
 */
status: IntentStatus, 
/**
 * Elapsed or settled time, e.g. `2M 14S` or `11.4S`.
 */
elapsed: string, };

/**
 * Why an intent was rejected. A variant rather than a sentence, so the form
 * can render on-voice copy per field.
 */
export type InvalidReason = "missing" | "malformed" | "out_of_range" | "too_precise" | "insufficient_funds";

/**
 * One rendered terminal line.
 *
 * `Box<str>` rather than `String`: these are built once, never mutated, and
 * arrive in the hundreds, so `String`'s spare-capacity word is dead weight.
 */
export type LogLine = { text: string, tone: LogTone, };

/**
 * Terminal line tone. Domain matches `TerminalLine`.
 */
export type LogTone = "out" | "dim" | "ok" | "err" | "info" | "loud";

/**
 * What the home screen renders.
 */
export type MeshSnapshotView = { 
/**
 * Truncated for display, e.g. `7F3A..8C2E`.
 */
nodeId: string, 
/**
 * Uptime in the board's format, e.g. `3D 14H 22M`.
 */
uptime: string, connected: boolean, stats: Array<StatTile>, };

export type ModeOption = { label: string, description: string, };

/**
 * A module-card NFT owned by a given wallet (used by the Redeem page, and
 * by `VAULT → MODULES`). Backed by a real `CabalMeshVoucher` tokenId
 * on-chain — "module card" is the name this type gives that token in every
 * Rust/TypeScript signature and every screen; the deployed contract itself
 * keeps its own name, `CabalMeshVoucher`, unchanged.
 */
export type ModuleCardView = { 
/**
 * u32 — see [`AssetListingView::id`]'s comment for why.
 */
tokenId: number, moduleType: string, description: string, owner: string, 
/**
 * The address that originally minted this card (proof-of-possession at
 * listing time) — lets the UI distinguish "I bought this from someone"
 * from "I minted this myself to sell and still hold it unsold".
 */
mintedBy: string, 
/**
 * 0 = RADIO, 1 = CRYPTO, 2 = POWER, 3 = SOULBOUND. Meaningless — always
 * `0` — on a non-module card (AI compute credit, etc.); `effect_bps`
 * being `0` is what actually says "nothing to equip here."
 */
slot: number, 
/**
 * 0 = COMMON, 1 = UNCOMMON, 2 = RARE, 3 = LEGENDARY.
 */
rarity: number, 
/**
 * The module's effect in basis points (1800 = +18%). Zero for
 * non-module cards.
 */
effectBps: number, };

/**
 * The `NODE LOADOUT` panel's data: what's equipped, and the multiplier it
 * actually produces right now.
 */
export type ModuleLoadout = { equipped: Array<EquippedSlot>, 
/**
 * Computed fresh from on-chain ownership on every call — see
 * `BlockchainBridge::get_relay_multiplier`'s docs for why this is
 * never cached.
 */
multiplier: number, };

/**
 * A peer, as the nodes screen shows it.
 *
 * **No distance.** A libp2p peer has an identifier and an address, not
 * coordinates, and this app requests no location permission — asking for one
 * would contradict the entire premise. The prototype's `1.2 km` is canned;
 * rendering it would be a fabricated measurement.
 */
export type NodeSummary = { 
/**
 * Truncated peer id, e.g. `8A3F..1209`.
 */
id: string, 
/**
 * Round-trip time where known.
 */
latencyMs: number | null, 
/**
 * 1 is direct; more means relayed.
 */
hops: number, transport: Transport, 
/**
 * Deterministic map position in [0,1], seeded by peer id.
 */
x: number, y: number, 
/**
 * Milliseconds, also seeded, so the field does not pulse in unison.
 */
pulseMs: number, };

/**
 * What the profile screen shows.
 */
export type ProfileView = { nodeId: string, 
/**
 * `14 (+55.6%)`, or just `14` with no prior window to compare against.
 *
 * Was a mocked `reputation` until ticket 39. Renamed along with the value
 * because a count called a "score" is a figure whose name promises more
 * than its definition delivers.
 */
settled: string, 
/**
 * `2026.08.03` — when this installation first ran.
 */
memberSince: string, offline: boolean, network: string, 
/**
 * Whether transactions here move real value.
 */
isTestnet: boolean, };

/**
 * A settlement proof hash. Displayed lowercase and unabbreviated.
 */
export type ProofHash = string;

/**
 * What the proof screen renders.
 */
export type ProofView = { id: string, 
/**
 * The settling transaction's hash.
 */
hash: string, 
/**
 * How long settlement took, e.g. `11.4S`.
 */
timing: string, 
/**
 * The hops the intent travelled. Empty when it settled directly.
 */
route: Array<string>, 
/**
 * The price it filled at. Absent for an unconditioned intent, which has
 * no price to have filled at.
 */
filledAt: string | null, };

/**
 * One row of the confirm dialog.
 */
export type ReviewRow = { key: string, value: string, };

/**
 * Current state of the vault's unlock method, for the startup gate and the
 * `SECURITY` screen.
 */
export type SecurityStatus = { 
/**
 * True only while the vault is passphrase-protected and no correct
 * passphrase has been supplied yet this session. The frontend gates
 * entry to the app on this field, not on `passphraseEnabled` alone —
 * `passphraseEnabled` stays true even seconds after a successful
 * unlock, when `locked` has already gone false.
 */
locked: boolean, passphraseEnabled: boolean, };

/**
 * What the splash screen needs to decide what it is offering.
 */
export type SessionStatus = { 
/**
 * Whether bootstrap has finished and the mesh is usable.
 */
ready: boolean, 
/**
 * Truncated node id, e.g. `7F3A..8C2E`. Absent before bootstrap.
 */
nodeId: string | null, 
/**
 * Whether a peer is reachable right now.
 */
connected: boolean, };

/**
 * A home-screen stat tile, pre-formatted.
 *
 * The frontend renders these verbatim. Sending a raw number and formatting it
 * there would mean reimplementing the separator and precision rules per
 * screen, and drifting from them.
 */
export type StatTile = { label: string, 
/**
 * Already separated, e.g. `1,248`.
 */
value: string, 
/**
 * Already signed and suffixed, e.g. `+12.4%`. Absent when unmeasured.
 */
delta: string | null, deltaTone: DeltaTone, };

/**
 * Status tone. Domain matches the design system's `StatusDot` prop exactly.
 */
export type StatusTone = "online" | "alert" | "info" | "idle" | "offline";

/**
 * Toast tone. Domain matches `Toast`.
 */
export type ToastTone = "neutral" | "info" | "success" | "alert";

/**
 * How a peer is reached.
 */
export type Transport = "mdns" | "quic" | "relayed" | "ble";

/**
 * A USD price, fixed at two decimal places — the precision the UI shows
 * (`$94.21`, `UNDER $95`).
 */
export type UsdPrice = { 
/**
 * Cents. Avoids the float rounding that makes price comparisons lie.
 */
cents: bigint, };

/**
 * A row in the vault list.
 */
export type VaultRow = { 
/**
 * Three-letter tag, e.g. `AVX`, `ID`, `KEY`.
 */
tag: string, name: string, amount: string, 
/**
 * Secondary line. Absent when there is nothing true to say.
 */
detail: string | null, };
